// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4TTUm-dGTQNjCnLMqkAS9Dn4VJp8oSlQ',
    appId: '1:1018562107558:web:9a04180e2f75866800fc67',
    messagingSenderId: '1018562107558',
    projectId: 'pushnotification-689e1',
    authDomain: 'pushnotification-689e1.firebaseapp.com',
    storageBucket: 'pushnotification-689e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlltS88XCEkDQ8xrjWpQFLWUFro916XKM',
    appId: '1:1018562107558:android:2b12ec46fbce313900fc67',
    messagingSenderId: '1018562107558',
    projectId: 'pushnotification-689e1',
    storageBucket: 'pushnotification-689e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzrvoiJIwF5WBQr0YYnbYLwaG_zlh8hA',
    appId: '1:1018562107558:ios:f4ba67c49b0c9d9600fc67',
    messagingSenderId: '1018562107558',
    projectId: 'pushnotification-689e1',
    storageBucket: 'pushnotification-689e1.appspot.com',
    iosBundleId: 'com.example.firebaseCrudNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzrvoiJIwF5WBQr0YYnbYLwaG_zlh8hA',
    appId: '1:1018562107558:ios:bb58f29aaab6e5b900fc67',
    messagingSenderId: '1018562107558',
    projectId: 'pushnotification-689e1',
    storageBucket: 'pushnotification-689e1.appspot.com',
    iosBundleId: 'com.example.firebaseCrudNew.RunnerTests',
  );
}
